"""create_initial_schema

Revision ID: 872f0be7f6dd
Revises: 
Create Date: 2026-10-07 10:11:46.239313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '872f0be7f6dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('training_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_version', sa.String(length=50), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_model_versions_name_version')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_demand', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_demand >= 0', name='ck_products_base_demand'),
    sa.CheckConstraint('unit_cost > 0', name='ck_products_unit_cost'),
    sa.CheckConstraint('weight_kg > 0', name='ck_products_weight_kg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=True)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('supplier_reliability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('base_lead_time', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_lead_time IS NULL OR base_lead_time > 0', name='ck_suppliers_base_lead_time'),
    sa.CheckConstraint('capacity IS NULL OR capacity >= 0', name='ck_suppliers_capacity'),
    sa.CheckConstraint('supplier_reliability >= 0 AND supplier_reliability <= 1', name='ck_suppliers_supplier_reliability'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_supplier_id'), 'suppliers', ['supplier_id'], unique=True)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('inventory_date', sa.Date(), nullable=False),
    sa.Column('inventory_level', sa.Integer(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('inventory_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("inventory_status IN ('Healthy', 'Low', 'Critical', 'Out of Stock')", name='ck_inventory_status'),
    sa.CheckConstraint('demand >= 0', name='ck_inventory_demand'),
    sa.CheckConstraint('inventory_level >= 0', name='ck_inventory_level'),
    sa.CheckConstraint('reorder_point >= 0', name='ck_inventory_reorder_point'),
    sa.CheckConstraint('safety_stock >= 0', name='ck_inventory_safety_stock'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_inventory_date'), 'inventory', ['inventory_date'], unique=False)
    op.create_index(op.f('ix_inventory_product_id'), 'inventory', ['product_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('actual_delivery_date', sa.Date(), nullable=False),
    sa.Column('lead_time', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('supplier_reliability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('inventory_level', sa.Integer(), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('transport_mode', sa.String(length=50), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('delay_days >= 0', name='ck_shipments_delay_days'),
    sa.CheckConstraint('demand >= 0', name='ck_shipments_demand'),
    sa.CheckConstraint('inventory_level >= 0', name='ck_shipments_inventory_level'),
    sa.CheckConstraint('lead_time > 0', name='ck_shipments_lead_time'),
    sa.CheckConstraint('order_date <= actual_delivery_date', name='ck_shipments_order_actual_date'),
    sa.CheckConstraint('order_date <= expected_delivery_date', name='ck_shipments_order_expected_date'),
    sa.CheckConstraint('quantity > 0', name='ck_shipments_quantity'),
    sa.CheckConstraint('shipping_cost >= 0', name='ck_shipments_shipping_cost'),
    sa.CheckConstraint('supplier_reliability >= 0 AND supplier_reliability <= 1', name='ck_shipments_supplier_reliability'),
    sa.CheckConstraint('unit_cost > 0', name='ck_shipments_unit_cost'),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_actual_delivery_date'), 'shipments', ['actual_delivery_date'], unique=False)
    op.create_index(op.f('ix_shipments_delay_days'), 'shipments', ['delay_days'], unique=False)
    op.create_index(op.f('ix_shipments_order_date'), 'shipments', ['order_date'], unique=False)
    op.create_index(op.f('ix_shipments_product_id'), 'shipments', ['product_id'], unique=False)
    op.create_index(op.f('ix_shipments_shipment_id'), 'shipments', ['shipment_id'], unique=True)
    op.create_index(op.f('ix_shipments_supplier_id'), 'shipments', ['supplier_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.String(length=50), nullable=False),
    sa.Column('shipment_id', sa.String(length=50), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('prediction_type', sa.String(length=100), nullable=False),
    sa.Column('predicted_value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('prediction_probability', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('prediction_status', sa.String(length=50), nullable=False),
    sa.Column('prediction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('prediction_horizon', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("prediction_type IN ('Delay Risk', 'Delivery Time', 'Inventory Shortage', 'Demand Forecast')", name='ck_predictions_type'),
    sa.CheckConstraint('prediction_probability IS NULL OR (prediction_probability >= 0 AND prediction_probability <= 1)', name='ck_predictions_probability'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.shipment_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=True)
    op.create_index(op.f('ix_predictions_shipment_id'), 'predictions', ['shipment_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.String(length=50), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_type', sa.String(length=100), nullable=False),
    sa.Column('recommendation_text', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("recommendation_type IN ('Expedite Shipment', 'Change Supplier', 'Increase Inventory', 'Reduce Order Quantity', 'Reorder Inventory', 'Monitor Supplier')", name='ck_recommendations_type'),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 1', name='ck_recommendations_confidence_score'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_prediction_id'), 'recommendations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=50), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=255), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decision_source', sa.String(length=50), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('decision_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision_source IN ('AI', 'Human', 'Rule', 'Optimization')", name='ck_decisions_source'),
    sa.CheckConstraint("status IN ('Pending', 'Approved', 'Rejected', 'Executed', 'Cancelled')", name='ck_decisions_status'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_decision_id'), 'decisions', ['decision_id'], unique=True)
    op.create_index(op.f('ix_decisions_recommendation_id'), 'decisions', ['recommendation_id'], unique=False)
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outcome_id', sa.String(length=50), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('actual_delay_days', sa.Integer(), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('inventory_impact', sa.Integer(), nullable=True),
    sa.Column('outcome_status', sa.String(length=50), nullable=False),
    sa.Column('success_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome_status IN ('Success', 'Partial Success', 'Failure', 'Pending')", name='ck_outcomes_status'),
    sa.CheckConstraint('actual_cost >= 0', name='ck_outcomes_actual_cost'),
    sa.CheckConstraint('actual_delay_days >= 0', name='ck_outcomes_actual_delay_days'),
    sa.CheckConstraint('success_score IS NULL OR (success_score >= 0 AND success_score <= 1)', name='ck_outcomes_success_score'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_decision_id'), 'outcomes', ['decision_id'], unique=False)
    op.create_index(op.f('ix_outcomes_outcome_id'), 'outcomes', ['outcome_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_outcome_id'), table_name='outcomes')
    op.drop_index(op.f('ix_outcomes_decision_id'), table_name='outcomes')
    op.drop_table('outcomes')
    op.drop_index(op.f('ix_decisions_recommendation_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_decision_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_prediction_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_predictions_shipment_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_shipments_supplier_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_shipment_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_product_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_date'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_delay_days'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_actual_delivery_date'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_inventory_product_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_inventory_date'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_suppliers_supplier_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
